### ISSUE TITLE
Publish on Homebrew on Linux 🍺🐧

### ISSUE THREAD

**Issue by TGotwig** [chmln/sd#102]
I would like to install this by [Homebrew on Linux](https://docs.brew.sh/Homebrew-on-Linux) 🐧
It's pretty straight forward to publish it there, for example I published 👉 [vidmerger](https://github.com/TGotwig/vidmerger) by that [formula](https://github.com/TGotwig/homebrew-linux-vidmerger/blob/master/vidmerger.rb) 📃

**Comment by TGotwig** [comment]
Created a working formula 👉 https://github.com/TGotwig/homebrew-linux-sd 🎉
Can be installed by:
```shell
brew tap tgotwig/linux-sd
brew install sd
```

**Comment by SimplyDanny** [comment]
There is already an official [Formula](https://github.com/Homebrew/linuxbrew-core/blob/master/Formula/sd.rb).
