### ISSUE TITLE
Feature request: ability to exit after one replacement

### ISSUE THREAD

**Issue by ngirard** [chmln/sd#105]
I ran against this situation multiple times: I only need to search & replace the first occurrence of a pattern.

It'd be useful if `sd` allowed to exit gracefully after performing one replacement.

There would be 2 benefits:
* better performance/efficiency;
* safety, as it would prevent unwanted replacements.

**Comment by sklages** [comment]
Why only the first? Maybe better - or somewhat "complete" - exit after **m** matches/replacements, default=1

**Comment by ngirard** [comment]
@sklages, sure.

I just meant to illustrate that this feature request originated from a specific, real-world situation of mine.

**Comment by anotatta** [comment]
So, is this documented on sd --help?
Now, I can only replace 1 match.  How about all matches?  
If I have to specify the number of matches, how do I know how many matches are there?

**Comment by balupton** [comment]
So https://github.com/chmln/sd/commit/687f3a5b1463886b0cbe926253497fd7c6ae447b has been merged, and has added a `-n` flag, however it doesn't work, `-n1` `-n 1` `-n=1` all error with:

```
error: Found argument '-n' which wasn't expected, or isn't valid in this context
```

```
> sd --version
sd 0.7.6
```

**Comment by balupton** [comment]
It would be cool if the occurrence flag allowed a range, such that this becomes much easier:

``` bash
echo $'a\nb\nc\na\nb\nc' | sd -n 2, '(?m:\nb$)' '' | sd '^b$)' 'B'
```

To get back:

```
a
B
c
a
c
```

**Comment by balupton** [comment]
Great that -n max was added in v1.0.0 🎉

Note that the range suggestion (as teip does) has not been added: https://github.com/greymd/teip/issues/27
