### ISSUE TITLE
Does this package overwrite default linux files? 

### ISSUE THREAD

**Issue by lcq92** [chmln/sd#106]
I noticed (on Manjaro Linux at least), that `man sd` returns something

```
SD(4)                                                                                          

NAME
       sd - driver for SCSI disk drives
(...)
```

Does that make this unsafe to install?

**Comment by tavianator** [comment]
Section 4 documents the devices in `/dev`.  That page specifically is talking about the device nodes for SATA drives, `/dev/sda` etc.  There's no `sd` binary associated with those.

**Comment by chmln** [comment]
Thanks @tavianator  :)
