### ISSUE TITLE
Underscores after $n capture replacements delete the rest of the line

### ISSUE THREAD

**Issue by Ben-Lichtman** [chmln/sd#108]
putting an underscore after the $n capture index seems to delete the entire capture instead of just inserting an underscore...

I have currently only tested this on windows powershell so this may be platform specific

```
PS C:\Users\me> echo "#include <asdf.h>" | sd '#include <(.*)\.h>' '#include \"$1.h\"'
#include "asdf.h"
```

```
PS C:\Users\ben> echo "#include <asdf.h>" | sd '#include <(.*)\.h>' '#include \"$1_v.h\"'
#include ".h"
```

**Comment by TheAlgorythm** [comment]
As the [documentation](https://github.com/chmln/sd#quick-guide) states, variable names can be segmented with curly brackets.
I changed your example and it worked on zsh.
```zsh
$ echo "#include <asdf.h>" | sd '#include <(.*)\.h>' '#include \"${1}_v.h\"'
#include "asdf_v.h"
```

**Comment by Ben-Lichtman** [comment]
Ah I missed that, thanks!
