### ISSUE TITLE
the musl binary for linux doesn't work

### ISSUE THREAD

**Issue by elkarouh** [chmln/sd#112]
I am on an old linux machine that i cannot upgrade.
The musl release is what i usually use for installing,eg, ripgrep or fd-rust
The musl release binary sd-v0.7.6-x86_64-unknown-linux-musl does not work.
Error message:
./sd-v0.7.6-x86_64-unknown-linux-musl: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./sd-v0.7.6-x86_64-unknown-linux-musl)

**Comment by dmitry-auto1** [comment]
```
$ sha1sum sd-v0.7.6-x86_64-unknown-linux-gnu 
01493bf75e54af2578340c164ee9c41f32861a13  sd-v0.7.6-x86_64-unknown-linux-gnu

$ sha1sum sd-v0.7.6-x86_64-unknown-linux-musl 
01493bf75e54af2578340c164ee9c41f32861a13  sd-v0.7.6-x86_64-unknown-linux-musl
```

**Comment by CosmicHorrorDev** [comment]
It looks like this should be fixed on the current `master`. I did a test run of publishing [here](https://github.com/CosmicHorrorDev/sd/releases/tag/1.0.0-pre-alpha.2), and the x64 linux musl asset does appear to actually link to musl

```bash
$ ldd sd-1.0.0-pre-alpha.2-x86_64-unknown-linux-musl
        statically linked
```

That means that this should be fixed with the next release
