### ISSUE TITLE
Wrong result when an echo with backslashes is piped to sd

### ISSUE THREAD

**Issue by homocomputeris** [chmln/sd#116]
```shell
$ echo '\newline' | sd 'l(\w+)e' 'page'

ewpage
$ echo '\newlimee' | sd 'l(\w+)e' 'page'

ewpage
```
instead of 
```shell
$ echo '\newline' | sd 'l(\w+)e' 'page'
newpage
$ echo '\newlimee' | sd 'l(\w+)e' 'page'
newpage
```

Meanwile, if ex.txt contains
```
\newline
\newlimee
```
then
```shell
$ cat ex.txt | sd 'l(\w+)e' 'page'
\newpage
\newpage
```

**Comment by SimplyDanny** [comment]
Can you please verify that the output of `echo '\newline'` does not already interpret the newline character? If it's like
```bash
$ echo '\newline'

ewline
```
then `sd` may not be the culprit. Different versions of `echo` show different behavior for escape sequences. Some interpret them, some only do it with the option `-e`.

**Comment by homocomputeris** [comment]
My bad then. Sorry.
