### ISSUE TITLE
Default [FILES] to all the files in current directory

### ISSUE THREAD

**Issue by klas-genestack** [chmln/sd#121]
I feel like modern CLI tools aiming for user's convenience (especially written in Rust, like `rg`, `fd`, `sk` (_skim_) etc) default to "all the files in current directory" (if it makes sense):
```
 sd [±:master] % rg replacement README.md
49:**Simple replacement on ~1.5 gigabytes of JSON**
61:**Regex replacement on a ~55M json file**:



 sd [±:master] % rg replacement
README.md
49:**Simple replacement on ~1.5 gigabytes of JSON**
61:**Regex replacement on a ~55M json file**:

src/cli.rs
25:    /// Limit the number of replacements
26:    pub replacements: Option<usize>,

src/main.rs
28:            options.replacements

src/replacer.rs
9:    replacements: usize,
18:        replacements: Option<usize>,
63:            replacements: replacements.unwrap_or(0),
84:                self.replacements,
90:                self.replacements,
174:    fn sanity_check_literal_replacements() {
179:    fn unescape_regex_replacements() {
184:    fn no_unescape_literal_replacements() {

build.rs
26:                .help("Emit the replacement to STDOUT"),

CHANGELOG.md
16:- `sd` now uses memory-mapped files, allowing replacement on files of any size
36:- Support for unicode and special characters (like `\n`) in replacement expressions
```

I personally keep wishing for such behaviour for `sd`.

**Comment by chmln** [comment]
@klas-genestack This is coming in next release with an `-r` flag for recursive find & replace.

**Comment by klas-genestack** [comment]
Nice!

But is there any reason to make that _a flag_?  I mean what's the point?  Right now running simple `sd 'a' 'b'` is absolutely useless and just hangs, so I think the behaviour I suggested improves usability considerably, doesn't it?

**Comment by chmln** [comment]
@klas-genestack good point. I've added logic to detect an interactive terminal and default to recursive replace now, much better.
