### ISSUE TITLE
How to filter rows and substitute (help)

### ISSUE THREAD

**Issue by ssvbio** [chmln/sd#128]
I would like to know if it is possible to replace in lines matching the pattern. Use case is as follows:

fasta sequence:

```
>seq1 foo
ATGC
>seq2 foo
CGAT
```

I would like to replace `foo` in header sequences. Sed would do as follows:
```
$ sed '/^>/ s/foo//' input.fa
```
I am aware that I can use **sd 'foo' '' input.fa**. However, I want this to happen only in headers to be careful. Does sd support filtering rows by pattern as sed does ? Thanks.

**Comment by SimplyDanny** [comment]
> Does sd support filtering rows by pattern as sed does ?

I don't think so. It just searches for patterns and replaces them.

What you can do is structure the regex in a way that it considers only headers containing `foo`. Your example could be formulated like `sd '^(>.*)foo(.*)' '$1$2'` with `sd`. I guess `sed` provides this two-way search as a convenience feature, but one can always do that in one step.

**Comment by MuhammadSawalhy** [comment]
I was searching for an issue before creating one, and I found this issue. I wish this feature will be added to the program, now we can use the other rust awesome **ripgrep** with **sd**

```bash
cat file | rg 'filter-pattern' | sd 'find' 'replacement'
```
