### ISSUE TITLE
Can you remove a line with sd?

### ISSUE THREAD

**Issue by EmilSodergren** [chmln/sd#132]
Is it possible to remove lines with sd? You could of course "replace line with empty" but that leaves unwanted empty blank lines. With sed you write `sed -i '/pattern to match/d' ./infile`. Is there something similar in sd? I think that functionality is the only thing that still keeps sed in my toolbox... :smile:

**Comment by murlakatamenka** [comment]
What about

```sh
sd '\n+' '' FILE
```
?

**Comment by jorunfa** [comment]
Just use '\n' in your pattern?

```
sd 'foo\n' ''
```

**Comment by balupton** [comment]
possible dupe of https://github.com/chmln/sd/issues/99

**Comment by CosmicHorrorDev** [comment]
As @jorunfa mentioned you just need to include the newline in the pattern. If you want to support text that uses `\r\n` as well then you can use `\r?\n`
