### ISSUE TITLE
Multiple replace operations in one go

### ISSUE THREAD

**Issue by blueray453** [chmln/sd#138]
How to run multiple replace in one go. For example, `sed -i 's/foo/bar/g; s/baz/zab/g; s/Alice/Joan/g' file`

How to replace multiple patterns with the same string. For example, Replace any of foo, bar or baz with foobar. In sed the command looks like: `sed -Ei 's/foo|bar|baz/foobar/g' file`

**Comment by ksandvik** [comment]
Yes, any option to add those on the command line or get the replacement patterns from a file? Would be handy, and I assume from a performance point of view more efficient?

**Comment by milahu** [comment]
duplicate of #133

**Comment by CosmicHorrorDev** [comment]
Trying to organize the issues more, so I'll be closing this as a duplicate of #133
