### ISSUE TITLE
Replace only if the string is found in a certain context

### ISSUE THREAD

**Issue by blueray453** [chmln/sd#140]
How can I replace `foo` with `bar` only if there is a `baz` later on the same line, For example, in sed the command looks like:

    sed -i 's/foo\(.*baz\)/bar\1/' file

Or, how can I replace `foo` with `bar` only if `foo` is found on the 3d field of the input file

**Comment by CosmicHorrorDev** [comment]
The command would be pretty similar to what you have with `sed`

```bash
$ cat issue.txt
foo qux baz
foo qux
foo baz
bar foo

$ sd --preview 'foo(.*baz)' 'bar$1' issue.txt
bar qux baz
foo qux
bar baz
bar foo
```

Pretty similar for your 3rd field question too. You match on two fields and try matching on foo, and then make sure to capture and include the first two fields in the output still

```bash
$ cat issue.txt
foo bar baz
a b foo
foo foo foo
a a a

$ sd --preview '(?P<before>(\w+) (\w+) )foo' '${before}bar' issue.txt
foo bar baz
a b bar
foo foo bar
a a a
```
