### ISSUE TITLE
Precompiled binaries not working on RHEL 7

### ISSUE THREAD

**Issue by daniejstriata** [chmln/sd#141]
Hi,

It would appear that the build system used is very current as I cannot run sd on RHEL 7.9 and Centos 7.9 which use glibc 2.17.

```
file /usr/local/sbin/sd
./usr/local/sbin/sd: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=d3422216ea260d328a5eff0031586cd3e87f4115, stripped
```

```
/usr/local/sbin/sd: /lib/libc.so.6: version `GLIBC_2.18' not found (required by /usr/local/sbin/sd)
	linux-vdso.so.1 =>  (0x00007ffca059e000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f355b52b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f355b30f000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f355b0f9000)
	libc.so.6 => /lib/libc.so.6 (0x00007f355ad2b000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f355aa29000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f355baf4000)
```

**Comment by daniejstriata** [comment]
I created a fork and uploaded the RPM and SRC.RPM here:
https://github.com/daniejstriata/sd/releases/tag/v0.7.6
I'm happy to upload new released there if you want to add to your releases.

**Comment by CosmicHorrorDev** [comment]
I've gone ahead and pushed a test release [here](https://github.com/CosmicHorrorDev/sd/releases/tag/1.0.0-pre-alpha.2). I'm not sure if that supports a lower glibc version like the error indicates, but at the very least there is a musl version that should work

There should be a new release out here soon, so I'm going to go ahead and close this

**Comment by daniejstriata** [comment]
I'll test on older distros and let you know if I run into anything.
