### ISSUE TITLE
character escapes in code are being followed by sd

### ISSUE THREAD

**Issue by vitiral** [chmln/sd#15]
After running sd on a file 

```
sd "ProjectPaths" "Settings" -i $somefile
```

This is an example diff:
```
-                    "INTERNALERROR: invalid html: {:?}\nERROR:{:?}",
+                    "INTERNALERROR: invalid html: {:?}
+ERROR:{:?}",
```

It looks like `sd` is interpreting the `\n` and using it when re-writing the file. I'm worried that other character escapes are also being treated in this way. I recommend doing extensive testing using a suite similar to the toml inputs

https://github.com/alexcrichton/toml-rs/blob/master/test-suite/tests/valid/string-escapes.json

I do roundtrip tests like this in stfu8, for example:
https://github.com/vitiral/stfu8/blob/master/tests/sanity.rs#L84

I also recommend running `sd` against unicode examples and asserting they don't change. You can see them in the .txt files here:
https://github.com/vitiral/stfu8/tree/master/tests

**Comment by chmln** [comment]
@vitiral which `sd` version are you using?

**Comment by vitiral** [comment]
a really, really old one (0.2.0)

**Comment by vitiral** [comment]
sorry, should have reinstalled.
