### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by Silentdoer** [chmln/sd#174]

**Comment by Nate-Wilkins** [comment]
Seems like the last commit was in April 2022. I mean I use it and like it way more than `sed`. :shrug:

**Comment by PeterlitsZo** [comment]
Should we fork it to be a community version?

**Comment by PeterlitsZo** [comment]
> Should we fork it to be a community version?

Well, I find that author replyed in another commit last month, so maybe it is not too good to fork another version.

But... the author do not reply this issue...

So I am not sure.

**Comment by CosmicHorrorDev** [comment]
@chmln I would be happy to help maintain this crate if that's considered desirable. I regularly use `sd`, and continuing maintenance of this crate is far preferred to forking

**Comment by chmln** [comment]
Hey guys,

Yes I would love to see more community involvement as my free time is unfortunately super limited these days. Let me know if you're interested on working on this crate and if you maintain any other rust packages and I'll be happy to provide maintainer permissions

**Comment by CosmicHorrorDev** [comment]
Thanks for the quick response. That's totally understandable!

I help maintain a [rather small number of crates](https://crates.io/users/CosmicHorrorDev), but I'm pretty active in the overall Rust ecosystem if you look at my github contributions. I'd be happy to start dealing with the backlog in the repo along with other typical maintenance tasks as time permits

**Comment by CosmicHorrorDev** [comment]
Thanks for the invite! I'll start working through the backlog tomorrow

**Comment by CosmicHorrorDev** [comment]
I think at this point we can consider the project to be maintained again (although more contributions are always welcome of course!)

**Comment by Nate-Wilkins** [comment]
@chmln I'd be happy to help as well. I'll start looking at the issues backlog too. Let me know if you want to prioritize anything that might not be listed there.

**Comment by CosmicHorrorDev** [comment]
We've got a lot of pending work that was held up on the release that just happened, so I would give a couple of days for that to all get worked through.

There are a lot of things that you could work on after some initial bits are sorted out. I'll be throwing up more issues over the next couple of days, so I'll mention you on them to see if you're interested

**Comment by dev-ardi** [comment]
We should add the "good first issue" tag to  help new contributors
