### ISSUE TITLE
How to prevent sd from adding a carriage return at the end of the line?

### ISSUE THREAD

**Issue by Schweber** [chmln/sd#175]
I'm using `sd` to change a list into a line. However, after doing that there is a carriage return at the end of the line which prevents me from computing the sum of all numbers with `bc`.

Why does `sd` do that and how can i prevent it?

```
~ ❯ cat weber | choose -2
-2904.2
-45.6
-160.7
-1513.0
+6250.1
+243.9
+324.1
+753.7
+121.6
~ ❯ cat weber | choose -2 | sd "\n" " "
-2904.2 -45.6 -160.7 -1513.0 +6250.1 +243.9 +324.1 +753.7 +121.6 ⏎
```

**Comment by PeterlitsZo** [comment]
What platform are you using?

I am running command below:

```
$ (echo -e '-1.1\n-1.2' | ./target/debug/sd "\n" " "; echo) | bc
-2.3
```

And the `sd` does not give the carriage at the end of the line.

That means I should put a newline token at the tail or bc will give an error. More detail will be helpful.

**Comment by michabs** [comment]
tested with:
>sed ':a;N;$!ba;s/\n/ /g' ./weber > weber_sed_output
>cat ./weber | sd "\n" " " > weber_sd_output
files weber_sd_output and weber_sed_output are the same

**Comment by Schweber** [comment]
I tested it and seem to be getting a carriage return also on other occasions. I'll look into it as according to your tests `sd` is not to blame.
