### ISSUE TITLE
How to use this to add text to the beginning of a file?

### ISSUE THREAD

**Issue by PaulRBerg** [chmln/sd#176]
Based on this [SO answer](https://superuser.com/q/246837/782478), this is how one can add text to the beginning o file using `sed`

```sh
sed -i '.bak' '1s/^/task goes here\'$'\n/g' todo.txt
```

How can one do the same thing with `sd`?

I have tried the following approaches; none worked:

- `sd "^" "content" file.txt` (this command added text both at the start and and at the end of the file)
- `sd "1^" "content" file.txt`
- `sd "1s/^" "content" file.txt`

Side note; would you be open to enabling [discussions]() in this repository? I would have preferred to open a discussion instead of an issue.

**Comment by Anangaya** [comment]
You can use the beginning of file anchor \A to do this.
`sd "\A" "content" file.txt`
To add to the end you can use
`sd "\z" "content" file.txt`

**Comment by PaulRBerg** [comment]
Thank you
