### ISSUE TITLE
Adding this package to the nixpkgs repo

### ISSUE THREAD

**Issue by abhi18av** [chmln/sd#18]
Hi @chmln ,

I'm trying to create a package for `sd` in the `nixpkgs` repo and I'm a bit stuck. Could you or anyone here help me out with this pull request here https://github.com/NixOS/nixpkgs/pull/54761

**Comment by Emiller88** [comment]
I believe https://github.com/NixOS/nixpkgs/commit/3679d1b17e1e2ba81eca459a7e41169542eb5203#diff-486b35e2ac004825847f0dc8532665cd

Closes this.
