### ISSUE TITLE
Feature: allow omit `<replace-with>` argument when empty string

### ISSUE THREAD

**Issue by rlb101001** [chmln/sd#180]
Now empty second argument raises error:
```
$ echo hello | sd e
error: The following required arguments were not provided:
    <replace-with>

USAGE:
    sd [OPTIONS] <find> <replace-with> [files]...

For more information try --help
```
Second empty argument is required:
```
$ echo hello | sd e ''
hllo
```
It would be wonderful if the following would work:
```
$ echo hello | sd e
hllo
```

**Comment by CosmicHorrorDev** [comment]
Currently I think the explicit nature of the current parsing is my preferred method. Keeping two separate values also gives an error message if someone tries invoking `sd` with `sed` arguments which could cause confusion otherwise

**Comment by rlb101001** [comment]
Empty string is as explicit as no parameter. If you want something explicit you have to require for example `echo hello | sd e 'hey, please, remove all matches... nice'` XD

**Comment by savochekchek** [comment]
Мне не помогло
![Screenshot_20241220-081447](https://github.com/user-attachments/assets/c187ec9c-040b-4894-a99e-99bc5c936bba)
