### ISSUE TITLE
sd replaces non-existent newline at the beginning of STDIN in powershell

### ISSUE THREAD

**Issue by desk7** [chmln/sd#198]
- sd 0.7.5
- Windows 10
- Powershell 7.3.4

In powershell the command
```powershell
"Hello
everyone!" |  sd  '\n' '\\n'
```
wrongly gives the following result:
```powershell
\nllo\neveryone!
```
Please note that the problem does not happen when processing a file in powershell.
I don't know if the problem depends on powershell or sd.

**Comment by PeterlitsZo** [comment]
This will help:

```PowerShell
"Hello
everyone!" | sd '\r\n|\n' '\\n'
```

If you just use `'\n'`, the token `'\r'` will not be replaced. It only happens in Windows. I think it maybe is a bug...

**Comment by PeterlitsZo** [comment]
Thanks, it is interesting... I will come back...

**Comment by CosmicHorrorDev** [comment]
I can reproduce the original issue (although I think we're all in agreement that it's expected behavior at this point): however, I can't reproduce the issue of `\r\n` remaining in the output string from `sd`

```
❯ echo -n "Hello\nHello\r\n" | sd '\n' 'A' | hexyl
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 48 65 6c 6c 6f 41 48 65 ┊ 6c 6c 6f 0d 41          │HelloAHe┊llo_A   │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

The above also matches what your observed output of

```
AelloAHello
```

since `\r\nA` in the output display as the initial A on the next line instead of all of it appearing on the same line

I don't have a windows machine setup that I can use for easy testing unfortunately, and I'm a bit pressed for time lately

**Comment by PeterlitsZo** [comment]
> 
> **but**, looking at the hex:
> `48 65 6c 6c 6f 41 48 65 6c 6c 6f 0d 0a 41 0d 0a`, that is
> 
> ```
> HelloAHello`r`nA`r`n
> ```

I build a rust application to reproduce this error:

```rust
use std::io::{stdin, Read};

fn main() {
    let mut s = Vec::new();
    stdin().read_to_end(&mut s).unwrap();
    for c in &s {
        print!("{:?} ", (*c as char));
    }
}
```

And this is the command run in the PowerShell:

```
> "Hello        
>> Hello" | sd '\n' 'A' | ./tmp.exe
'H' 'e' 'l' 'l' 'o' 'A' 'H' 'e' 'l' 'l' 'o' '\r' '\n' 'A' '\r' '\n' 
> "Hello
>> Hello" | ./tmp.exe
'H' 'e' 'l' 'l' 'o' '\n' 'H' 'e' 'l' 'l' 'o' '\r' '\n' 
```

The reason for this question is now clear:

- `sd` give us `'H' 'e' 'l' 'l' 'o' 'A' 'H' 'e' 'l' 'l' 'o' '\r' 'A'`
- PowerShell turns the `\r` into `\r\n`.
- PowerShell also appends a `\r\n` at the end of the text if it doesn't find a `\r\n` at the end.

I didn't find a document about this behavior. But I think it is right after some tests.

**Comment by CosmicHorrorDev** [comment]
Seems good. Thanks for digging into this more @PeterlitsZo!

**Comment by PeterlitsZo** [comment]
But I think we can add a flag or something to use `\n` to catch `\n` and `\r\n`. Do you think it is a good idea? That can make us use the same command in both Windows and UNIX-like OS.

**Comment by CosmicHorrorDev** [comment]
Hmmm, I'll have to think about that more for now
