### ISSUE TITLE
Dry-run mode

### ISSUE THREAD

**Issue by franky47** [chmln/sd#20]
In ZMV there is the `-n` option flag that shows you what the output would be, without actually doing anything. It is very handy for fine-tuning the regexp before actually commiting the replacement to disk.

However, whenever I want to use it I can't seem to remember that it's `-n`, so maybe it's not the best choice. The expanded `--dry-run` would make more sense.

**Comment by chmln** [comment]
@franky47 I believe there is already a dry-run mode. If you run, say, `sd "abc" "def" file.txt` without `-i`, the result will simply be emitted to stdout

**Comment by franky47** [comment]
Indeed, thanks !

**Comment by tmerse** [comment]
Should be added that `-p, --preview` takes care of this (the default is to change files).

**Comment by james2doyle** [comment]
Could `-p, --preview` be aliased as `--dry-run` just to cover this case?
