### ISSUE TITLE
Please consider bumping to 1.0

### ISSUE THREAD

**Issue by nc7s** [chmln/sd#200]
The reasoning is twofold.

First, I maintain the sd package [in Debian](https://tracker.debian.org/sd). A Debian Developer recently filed [a bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037192) due to its version being "too low" to keep the monotonically increasing version constraint of the Debian archive. There was once another sd package in Debian, which as the bug stated had a highest version of 0.74.

Now I can use an [epoch](https://www.debian.org/doc/debian-policy/ch-controlfields.html#epochs-should-be-used-sparingly) (basically adding `1:` to the usual semver, so it becomes `1:0.7.6` for instance, which is higher than the implicit initial `0:`), or rename the package to something else, like rust-sd. But using epoch means [stable-updates](https://wiki.debian.org/StableUpdates) and renaming means going through the [NEW queue](https://wiki.debian.org/NewQueue) again, and I'm lazy :P

Second, this project seems mature enough, the last release on crates.io dates back to August 2020. It definitely deserves a 1.0 mark.

**Comment by CosmicHorrorDev** [comment]
>Second, this project seems mature enough, the last release on crates.io dates back to August 2020. It definitely deserves a 1.0 mark.

I would be up for bumping to 1.0 sometime soon, but the next release will be a breaking release, and I'm not sure if that will be the only breaking release coming soon

**Comment by bnoctis** [comment]
Not sure because? I can do some coding if appropriate.

**Comment by CosmicHorrorDev** [comment]
Mostly because I only recently took over maintenance, so there may be issues down the line that will require a breaking change to deal with. That being said I think things are stable enough to warrant 1.0 here soon, and we can just bump to 2.0 if more breaking changes are needed later

**Comment by bnoctis** [comment]
Great, tag me anytime when in need of PRs ;)
