### ISSUE TITLE
Multi-line matching broken?

### ISSUE THREAD

**Issue by MaxGyver83** [chmln/sd#202]
I want to replace a whole HTML div tag.

Example file (`test.html`):

```html
<div>
  <p>hello</p>
</div>
```

Shouldn't this match and replace all three lines with `xxx`?

```sh
sd -f m '<div>.*</div>' xxx test.html
```

It doesn't replace anything.

**Comment by CosmicHorrorDev** [comment]
`.` matches _almost_ any character. From: https://www.regular-expressions.info/dot.html (emphasis mine)

> ...
> 
> The dot matches a single character, without caring what that character is. **The only exception are line break characters.** In all regex flavors discussed in this tutorial, the dot does not match line breaks by default.
> ...

**Comment by CosmicHorrorDev** [comment]
Got around to testing and the (rather unfortunately named) single-line mode flag causes this to work as intended

```text
$ cat test.html
<div>
  <p>hello</p>
</div>

$ sd -f s -p '<div>.*</div>' xxx test.html
xxx
```

**Comment by MaxGyver83** [comment]
Sure, by default the dot does not match newline characters. But I understood the multi-line regex flag in a way that it allows to match newlines as well. Then I suppose it's more like Python's `re.MULTILINE`, not `re.DOTALL`, right?

**Comment by MaxGyver83** [comment]
> Got around to testing and the (rather unfortunately named) single-line mode flag causes this to work as intended

This works. Thank you! My man page must be outdated: It lists only the flags `c`, `i`, `m`, and `w`. (I'm using version 0.7.6 on Arch Linux.) But I wouldn't have guessed that I need "single-line mode" instead of "multi-line matching".

**Comment by CosmicHorrorDev** [comment]
Yeah, unfortunately the naming is pretty terrible, but consistent with other regex implementations

At the very least the `--help` text covers it, but the man page is currently out of sync in a few ways (#134). I've got it on my list for fixing before the next release, but I'm pretty short on time lately

**Comment by MaxGyver83** [comment]
I just checked `--help` and the explanation of the `s` flag is perfectly clear 👍

> s - make `.` match newlines
