### ISSUE TITLE
Passing the preview flag when inputing from stdin doesn't make sense

### ISSUE THREAD

**Issue by dev-ardi** [chmln/sd#222]
It should either fail completely or send a warning to stderr at least

**Comment by nc7s** [comment]
What do you mean by "passing the preview flag when outputing to stdout"? If I understand correctly, it's the flag that makes sd output to stdout, right?

**Comment by dev-ardi** [comment]
Oops, I meant inputing from stdin. as in `sd find replace --preview`
```
$ sd --preview a x
ardi
xrdi
```
as it's redundant
