### ISSUE TITLE
notabug - just a 'thanks!'

### ISSUE THREAD

**Issue by atomGit** [chmln/sd#223]
thanks to all who work on this project - after fooling around for a very long time with sed, perl (no, \Q\E _cannot_ be counted on) and ruby to search/replace arbitrary complex blocks in text in a file, sd worked on the 1st try, no --help needed!

**Comment by CosmicHorrorDev** [comment]
Thanks for your appreciation! I'm also very grateful for everyone who works on this project :slightly_smiling_face:
