### ISSUE TITLE
Why hasn't there been a release for SD since 2020?

### ISSUE THREAD

**Issue by YousufSSyed** [chmln/sd#247]
Looking at the [releases page](https://github.com/chmln/sd/releases) the last one was 0.7.6 back in 2020. I looked at the readme which says to use `-F` or `--fixed-strings` and I was super confused why it wasn't working after I recently installed sd with homebrew.

**Comment by CosmicHorrorDev** [comment]
I'm working on getting a release out, but I'm stretched thin on time. I have this entire weekend free to work on it

As for the README it is confusing that the repo's README differs from the version of `sd` that you have installed, but that's pretty typical when it comes to open source projects where the repo includes unstable or unreleased changes. You can always select the v0.7.6 tag if you want to see the state of the repo for that specific version

**Comment by YousufSSyed** [comment]
@CosmicHorrorDev why has it been three years though?

**Comment by CosmicHorrorDev** [comment]
Because the lead maintainer stopped maintaining it likely due to being too busy with other work and I took over as maintainer relatively recently and have been very busy lately which leaves limited time and energy for this project (moving, `$WORK`, other projects, etc.)
