### ISSUE TITLE
Can't install sd on macOS High Sierra

### ISSUE THREAD

**Issue by chapeupreto** [chmln/sd#25]
I'm having some trouble installing `sd` on `macOS High Sierra` **(version 10.13.6)**

I'm using `rustc 1.25.0 (84203cac6 2018-03-25)` and I got the error message below when issuing `cargo install sd --verbose`:

Caused by:
  Could not compile `sd`.

Caused by:
  process didn't exit successfully: `rustc --crate-name sd src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C metadata=eeddc918bbb61feb -C extra-filename=-eeddc918bbb61feb --out-dir /var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps -L dependency=/var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps --extern rayon=/var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps/librayon-50e0ecc9ad3d9d0e.rlib --extern regex_syntax=/var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps/libregex_syntax-4ecf4d4c9b0429f8.rlib --extern regex=/var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps/libregex-0ea6cc294b773273.rlib --extern structopt=/var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps/libstructopt-a1bdebfe50528146.rlib --extern unescape=/var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps/libunescape-830b9c63499749ae.rlib --extern atomicwrites=/var/folders/p2/kcd723157t98hxc8sd1rj3k40000gn/T/cargo-install.Nlorfacc8Jcq/release/deps/libatomicwrites-e8bbeb4fdf1f5771.rlib --cap-lints allow` (exit code: 101)

Awesome project, anyway.  👍

**Comment by chmln** [comment]
Hey, it may be worth to try again with an updated rust version. The current stable is v1.33

```
rustup update
cargo install sd
```

**Comment by chapeupreto** [comment]
It works now. 👍

When installing via cargo, maybe it would be nice to have something like `Note that rust version 1.33.0 or later is required.` on the README file.

Thanks, man.
