### ISSUE TITLE
Friendly ping to Arch packagers

### ISSUE THREAD

**Issue by CosmicHorrorDev** [chmln/sd#278]
Hiya @svenstaro! I see you maintain the Arch package for `sd`. I noticed that the package was already flagged out of date, but I've gone ahead and adapted the existing PKGBUILD to handle the recent packaging changes if you want to steal that (the man page and completions are now all generated ahead of time instead of at build time)

https://github.com/CosmicHorrorDev/arch-pkgbuilds/commit/473d28dce07cd01a3d6bb4c4cdde004fc2d77cee

Also worth noting that we do also generate completions for powershell and elvish as well, but I don't know the standard locations that those completions would go in

**Comment by alerque** [comment]
System paths for Elvish shell completions can be seen here: https://github.com/elves/elvish/issues/1004

**Comment by alerque** [comment]
1.0.0 is in [extra-testing]. Feel free to give it a spin. And congrats on the major release.

**Comment by CosmicHorrorDev** [comment]
> Feel free to give it a spin.

Seems to be working great!

> And congrats on the major release.

Thanks :)
