### ISSUE TITLE
Feature Request: renaming files?

### ISSUE THREAD

**Issue by pickx** [chmln/sd#289]
it would be nice to be able to use `sd` to rename file(s), especially in bulk: 
something like `sd --rename before after *.zip` would rename all the files that match that glob instead of modifying their contents. (I have no strong feelings about how this syntax should look like).

yes, this is fairly trivial to do (by piping or variable assignment), and not something that `sed` is typically used for.
however, existing solutions which you would be encouraged to use here instead of `sed`, either use `sed`-like syntax for renaming (such as the `rename` program), or built-in shell commands. I would like to move away from having to use syntax like that.

**Comment by CosmicHorrorDev** [comment]
Personally I'd say this functionality seems too far away from what I would expect from `sed` or `sd`. It seems much better suited to `-exec`/`-exec` with `find`/`fd`

**Comment by nc7s** [comment]
You may be interested in https://github.com/ismaelgv/rnr.

**Comment by pickx** [comment]
> You may be interested in https://github.com/ismaelgv/rnr.

that seems to do exactly what I want! thanks. 
closing this since I no longer have a need for this.
