### ISSUE TITLE
[PENDING] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [chmln/sd#30]
Dear Gregory,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by Tragen** [comment]
That would be great if you could compile a windows version.

**Comment by ThePumilio** [comment]
A windows version would help me a lot. Is the best tool

**Comment by chmln** [comment]
Hey guys, the latest release is now available for Windows! See https://github.com/chmln/sd/releases/tag/0.6.4

Please test it out and let me know if something isn't working.
