### ISSUE TITLE
[Resolved] Regex replace with literal dollar sign is not possible

### ISSUE THREAD

**Issue by agustinuslaw** [chmln/sd#303]
Powershell variables starts with '$', so there may be a lot of replacement that results in some variable.

For example suppose we want to replace from:
`Write-Log "Some logging" -l $LogPath`
to:
`$Logger.log("Some logging")`

How might I replace the replacement '$' so that this works? I have tried, no escapement `'$'`, escaping with `'\$'`, and escape with "`$".
But they all result in the '$Logger' part being removed. See below example.

```
PS C:\> 'Write-Log "Some logging" -l $LogPath' | sd -p -f c 'Write-Log (.*?) -l \$LogPath' '$Logger.log($1)'
.log("Some logging")
PS C:\> 'Write-Log "Some logging" -l $LogPath' | sd -p -f c 'Write-Log (.*?) -l \$LogPath' '\$Logger.log($1)'
\.log("Some logging")
PS C:\> 'Write-Log "Some logging" -l $LogPath' | sd -p -f c 'Write-Log (.*?) -l \$LogPath' "`$Logger.log(`$1)"
.log("Some logging")
```

Is there an escapement method that I must use?

Edit1: backticked the escapement symbols.

**Comment by agustinuslaw** [comment]
Nevermind, found an escapement that works `$$`

**Comment by dev-ardi** [comment]
Which one?

**Comment by agustinuslaw** [comment]
_Which one?_ --> After using `$$` escape in the `<REPLACE_WITH>` field it works (see below), though a bit unexpected. 
Why not also use `'\$'` to escape both pwsh and regex like the the `<FIND>` field?

`PS C:\> 'Write-Log "Some logging" -l $LogPath' | sd -p -f c 'Write-Log (.*?) -l \$LogPath' '$$Logger.log($1)'
