### ISSUE TITLE
Ignore directory arguments

### ISSUE THREAD

**Issue by sharkdp** [chmln/sd#33]
I think it would be great if `sd` would silently ignore directory arguments. This would allow easier integration with shell globs and external tools like `find`/`fd`.

Suppose I have the following structure:
```
▶ mkdir dir; echo "foo" > file; echo "foo foo" > dir/other_file
▶ tree
.
├── dir
│   └── other_file
└── file
```

Now I want to replace `foo` by `bar`, recursively. It'd be great if I could just call
```
▶ sd foo bar **/*
```

However, this currently fails with:
```
Error: Is a directory (os error 21)
```

Interestingly, everything works with `--in-place` mode:
```
▶ sd -i foo bar **/*
```

Admittedly, `--in-place` is almost always what I want if I supply any arguments, but I wonder if the normal (not in-place) mode should behave the same.

Thinking of this, would it be an option to enable `--in-place` by default (if `sd` is not reading from STDIN)? Or would you consider this to be too dangerous?

Awesome tool, by the way - Thank you!

**Comment by chmln** [comment]
@sharkdp thanks for the feedback, and I agree with most of what you outlined.

--in-place is going to become the default in the near future and --preview will instead become the modifying flag (#31)

**Comment by sharkdp** [comment]
> --in-place is going to become the default in the near future and --preview will instead become the modifying flag (#31)

That sounds great!

**Comment by chmln** [comment]
Released in v0.6

**Comment by sharkdp** [comment]
Thank you very much for the updates. In-place by-default works as expected, but `sd` still outputs errors when presented with dictionaries:
```
▶ sd test TEST src/main.rs src 
No such device (os error 19)
```

**Comment by chmln** [comment]
@sharkdp yes, `sd` still operates exclusively on files. The problem with allowing directories to be passed in (even if they just get ignored) is that users might mistake them for some sort of recursive find & replace.

Now whether this sort of recursive replacement on directories should be added is a different question altogether. What do you think? I personally just use `sd abc def $(fd -t f)`.

**Comment by sharkdp** [comment]
> @sharkdp yes, `sd` still operates exclusively on files.

that's ok. I just think that the "no such device (os error 19)" warning message could be confusing to users. 

> Now whether this sort of recursive replacement on directories should be added is a different question altogether. What do you think? I personally just use `sd abc def $(fd -t f)`.

Recursive find & replace in the current directory is probably my number one use-case, so I think it would be great if it would be natively supported by `sd`. On the other hand, it would probably also add a lot of code (and potentially new command line options) to `sd`, so I'm not sure if it should really be added. It already plays nicely with `find`, `fd`, recursive globs, etc.

**Comment by sharkdp** [comment]
> I personally just use `sd abc def $(fd -t f)`.

Another cool workflow is the following: use `fd` to find a set of files and double-check if you don't have any wrong matches. Then, instead of putting the whole command in a `$(…)` subshell, just append `-X sd …`:
``` bash
▶ fd mod.rs         
src/exec/mod.rs
src/fshelper/mod.rs
src/internal/filter/mod.rs
src/internal/mod.rs
tests/testenv/mod.rs

▶ # oh, let's exclude the ones from "internal"
▶ fd mod.rs -E internal
src/exec/mod.rs
src/fshelper/mod.rs
tests/testenv/mod.rs

▶ # now call 'sd':
▶ fd mod.rs -E internal -X sd foo bar
```
