### ISSUE TITLE
Easy way to replace full words

### ISSUE THREAD

**Issue by sharkdp** [chmln/sd#35]
Let's say I want to rename a variable/function/class/etc. I want to change the name from `foo` to `bar`. But obviously, I don't want to replace any occurrences of the word `fool` by `barl` (can't think of a better example right now). I can solve this by adding `\b` word boundary markers around the pattern:
```
sd '\bfoo\b' bar …
```

However, since this is such a common scenario and such an easy thing to get wrong, I think it would be great if `sd` would feature a command-line option to do this automatically (maybe `-w`/`--word` or `-b`/`--boundary`). I think this would look much better and would be easier to type:
```
sd -b foo bar …
```

**Comment by chmln** [comment]
Added in v0.6: `sd -f w foo bar`

**Comment by sharkdp** [comment]
Thank you!
