### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by xzn** [chmln/sd#37]
Currently `-i` switch doesn't work on Windows.

Error when replacement string is longer than matched string: `failed to write whole buffer`
Error otherwise: `failed to persist temporary file: Access is denied. (os error 5)`

**Comment by sharkdp** [comment]
A similar bug appears on Linux as well: #38.

**Comment by chmln** [comment]
@xzn could you please check if the issue is still present in v0.6.1?

**Comment by xzn** [comment]
The `failed to write whole buffer` issue is fixed.

For the second issue after a bit of testing `mmap_source` and `source` need to be dropped before the call to [`persist`](https://github.com/chmln/sd/commit/ab457f7c70384722a3d77c228fe291d98f7b59c1#diff-d678f39ca56a471bfa2efbcdfcf593b0R115).
