### ISSUE TITLE
0.6.4 empty output when regex does not match

### ISSUE THREAD

**Issue by chris-cummings-eb** [chmln/sd#42]
```
$ echo hello | sd j ''

$ echo hello | sed 's/j//g'
hello
```
This is new behavior that was introduced after upgrading this package via homebrew today. I'm not sure which version I was running before, but probably the immediately previous release or two.

The behavior used to match sed in this case. I'm not sure what's intended, but I wanted to file an issue incase it was helpful.

**Comment by chmln** [comment]
Hey, thanks a lot for reporting this @chris-cummings-eb !

I've released v0.6.5 with the fix.
