### ISSUE TITLE
Ppublish sd to ubuntu apt

### ISSUE THREAD

**Issue by eromoe** [chmln/sd#47]
`apt install sd`  doesn't work . 

I have found that cargo is need before install sd. 
Do you have a plan publish sd to ubuntu apt ?

**Comment by chmln** [comment]
@eromoe Unfortunately I don't have the time to package `sd` for specific operating systems or distributions. Perhaps someone from Debian will package it soon as well and eventually it will reach Ubuntu.

**Comment by chmln** [comment]
Keeping this open for tracking purposes.

**Comment by curquiza** [comment]
+1

**Comment by CosmicHorrorDev** [comment]
As @nc7s pointed out it looks like `sd` is now included in ubuntu's repos. This is also reflected in the repology badge on the README which has `sd` v0.7.6 in Ubuntu 23.04 and 23.10
