### ISSUE TITLE
Support `s` flag, which makes `.` match `\n`

### ISSUE THREAD

**Issue by casey** [chmln/sd#49]
I recently wound up wanting the `s` flag, which makes `.` match `\n`. Is the `s` flag something that `sd` could support?

It might be nice to support all of the regex crate's flags, unless particular flag because it doesn't work in the context of `sd`.

PS Thank you for sd! I like it a lot ^_^

**Comment by crides** [comment]
Second this. Otherwise we'll have to do the `[\s\S]` trick, which is much longer and harder to read.
