### ISSUE TITLE
Create MUSL Build

### ISSUE THREAD

**Issue by mathomp4** [chmln/sd#56]
I was wondering if it it would be possible to create a MUSL build of `sd` along with the GNU build. I ask only because I'd like to use `sd` on a system (supercomputing cluster) that hasn't quite kept up with the latest Linux for stability reasons:
```
(1332) $ sd --version
sd: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by sd)
```
This happens a lot with all the nice rust apps I use now (`ripgrep`) and the usual fix I have is to grab the MUSL build instead of the GNU build. (Or I guess, [I bug..uh..ask them to add MUSL](https://github.com/starship/starship/issues/303) a la `starship`...and here! :smile: )

**Comment by chmln** [comment]
@mathomp4 Yes, for sure, thanks for reminding me.
