### ISSUE TITLE
sd fails to match when using `^` to delimit the beginning of the line

### ISSUE THREAD

**Issue by Porkepix** [chmln/sd#60]
When trying some search & replace where I wanted to match something only if the line was starting with it, I wanted to use the usual `^` to flag the beginning of the line. The result was a fail of the match wail getting rid of it resulted in fine matching.
I tried to escaping it, guessing that as `$` is used for variables, it probably needs some escaping to flag the end of a line the same way, but this didn't work as well.

I guess that `^`and `$` should somehow be usable to flag beginning and end of the line.

**Comment by Gutem** [comment]
Yep. My `sed` regex to match HTML Tags `<[^>]*>` doesn't work.

**Comment by seebye** [comment]
I ran into the same issue.  
Also I noticed that it works as expected on the first line,  
so I enabled the multiline flag and it worked as expected afterwards.  
E.g. shell history without line numbers:  
```bash
history | sd -f m '^\s*[0-9]+\s+' '' | less
```

**Comment by chmln** [comment]
Thanks for reporting this @Porkepix. I also believe the multi-line flag makes more sense to have as a default, similar to `sed`.
