### ISSUE TITLE
No support for globs?

### ISSUE THREAD

**Issue by bottiger1** [chmln/sd#67]
D:\openvpn\config>sd a b *.txt
The filename, directory name, or volume label syntax is incorrect. (os error 123)

**Comment by AndydeCleyre** [comment]
Globbing is a feature of the shell itself, and if it's working, `sd` itself should never see that asterisk, only the result of the shell's expansion of it.

What shell are you using?

**Comment by CosmicHorrorDev** [comment]
As mentioned globbing is handled by the shell. On windows you can use git bash or WSL to get easy access to different shells that do support globbing

**Comment by sergeevabc** [comment]
Why is this issue closed if SD still does not know how to work properly with `*.ext` under Windows?

``` console
$ sd.exe -p -F "foo" "bar" *.txt
error: The filename, directory name, or volume label syntax is incorrect. (os error 123)

$ sed.exe -i "s/foo/bar/g" *.txt
It works!
```

**Comment by Anangaya** [comment]
Git bashes globing will fail if it matches too many files because of the windows command line length limitation. So this mush have feature.

**Comment by sergeevabc** [comment]
Aggrrhh! This issue should be re-opened.
