### ISSUE TITLE
Installing on Windows with Chocolatey

### ISSUE THREAD

**Issue by mardukbp** [chmln/sd#69]
My CLI Swiss Army knife includes ripgrep, fd and fzf. And now sd. The first three can be installed on Windows with Chocolatey, which makes it easy to tell my friends and colleagues to check them out. It would be great to spread the word about sd too :)

**Comment by SimplyDanny** [comment]
I guess this is more a topic for Chocolatey than for sd. You may instead create a package request [here](https://github.com/chocolatey-community/chocolatey-package-requests).

**Comment by mardukbp** [comment]
Done. Thank you for providing the link. I will close this issue when the package becomes available.

**Comment by mardukbp** [comment]
The [Chocolatey package](https://www.chocolatey.org/packages/sd-cli) is ready! I just submitted the PR #78 to update the README.
