### ISSUE TITLE
WinGet-based installation

### ISSUE THREAD

**Issue by zkat** [chmln/sd#90]
It would be really great to be able to install sd on Windows through the [windows package manager, `winget`](https://docs.microsoft.com/en-us/windows/package-manager/winget/).

**Comment by chmln** [comment]
@zkat pull requests are welcome!

**Comment by CosmicHorrorDev** [comment]
It looks like this is now resolved as of https://github.com/microsoft/winget-pkgs/pull/123051 :tada:

Currently it's an older version of `sd`, but I've already notified them of that, so I'm sure that will get sorted out over time
