### ISSUE TITLE
When using sd over a symlink, symlink get replaced by a full-featured file

### ISSUE THREAD

**Issue by Porkepix** [chmln/sd#94]
As stated in the issue title, when sd is used over a symlink, the symlink gets replaced with a complete file rewrited over it, copy of the file the symlink was pointing to.

**Comment by eddy-geek** [comment]
@chmln can we have a release including this fix? thanks!

**Comment by coolaj86** [comment]
Could we get a new release with this?

**Comment by tekumara** [comment]
@CosmicHorrorDev could we please release this? 🙏

**Comment by CosmicHorrorDev** [comment]
There will be a release when all the issues on the v0.8.0 milestone are resolved (although I may bump a few back to the v0.8.1 milestone looking over the list again)

I've got a lot on my plate for the next month including moving, so there likely won't be a release until the middle of July
