### ISSUE TITLE
Arm64 releases?

### ISSUE THREAD

**Issue by mathomp4** [chmln/sd#98]
I'm beginning to explore using Arm64 on AWS. I always grab my favorite Rust utils and the only one missing is `sd`. Do you think it would be possible to have an Arm64 release of sd made?

Aka: I love `sd` to much to remember `sed` 😄

**Comment by chmln** [comment]
@mathomp4 of course ! I will try to have it ready for the next release soon

**Comment by mathomp4** [comment]
> @mathomp4 of course ! I will try to have it ready for the next release soon

Thanks! I'll gladly test. I tried some of my others and had...limited success. I think only fd-find worked, but rg and dust didn't. I'm not sure what I might have done wrong. I can be your guinea pig.

**Comment by yhakbar** [comment]
Hey @chmln , did you run into any roadblocks with this? Anything the community can help with?

**Comment by yhakbar** [comment]
I cut a release on my fork to support this, as I needed this for support on Graviton instances:
https://github.com/yhakbar/sd/releases/tag/v0.7.7-yhakbar

Hopefully, once https://github.com/chmln/sd/pull/179 is merged in, we can fetch a release on this repo.

**Comment by CosmicHorrorDev** [comment]
This should be fixed with the next release which should be coming very soon. I'm going to go ahead and close this to keep the issue tracker easier to follow
